### ISSUE TITLE
Estructurar proyecto en Go

### ISSUE THREAD

**Issue by jlgallego99** [jlgallego99/OSTfind#13]

**Comment by JJ** [comment]
No necesitas un punto de entrada a la aplicación (ni está solicitado por ningún HU)

**Comment by JJ** [comment]
Tampoco justificas por qué usas "internal" como directorio base.

**Comment by jlgallego99** [comment]
Era más que nada por si lo necesitaba en el futuro, pero visto que no, lo corrijo en la tarea #38. El uso de la estructura del proyecto se ha justificado en el commit bf3fd5e añadiendolo como parte de la documentación del proyecto
