### ISSUE TITLE
Los agregados son clases que incluyen entidades y objetos valor

### ISSUE THREAD

**Issue by JJ** [jlgallego99/OSTfind#33]
Y me da la impresión de que en este caso lo que has hecho ha sido poner los resultados de la lógica de negocio en objetos específicos. 

https://github.com/jlgallego99/OSTfind/blob/2eb3b6496e0c38f1ebc95400efc32d2b3406d7df/docs/ddd.md?plain=1#L20-L31

**Comment by jlgallego99** [comment]
Creo que ya he entendido bien los conceptos de entidad, objeto valor y agregados y los he podido aplicar bien a mi proyecto. Agradezco cualquier feedback que me pueda dar de si realmente lo he entendido bien o hay cosas que puedo cambiar. Todo está referenciado en el documento [ddd](https://github.com/jlgallego99/OSTfind/blob/hito-2/docs/ddd.md) y se está desarrollando en las tareas #39 #40
